apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    devEnvApprovers:
    - joostvdg
    environmentGitOwner: joostvdg
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: joostvdg
    repository: jx3-kubernetes-demo
  - key: staging
  - key: production
  ingress:
    domain: pmgke.kearos.net
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: joostvdg@gmail.com
      enabled: true
      production: true
  pipelineUser:
    username: joostvdg
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
